### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by ghost** [deleisha/evt-tls#10]
Is evt-tls dead or will stuff happen?

Seems like it's bug-ridden, incomplete, and undocumented. But there doesn't seem to be SSL alternatives for libvu.

**Comment by deleisha** [comment]
It is not dead for sure but slow but due to unavailability of work. Would appreciate any collaborator

**Comment by deleisha** [comment]
Closing this as this is a query which, I believe, have been answered
