### ISSUE TITLE
do you think uv_multiplex would work in conjuction with this?

### ISSUE THREAD

**Issue by ljackson** [deleisha/evt-tls#14]
Asking because I wanted to know your opinion. I am looking for a multithreaded high perf TLS stream to msg parsing framework and so far your abstraction on openssl for async and the example for libuv looks like a potential win (obviously with a lot of work to switch from echo and make more production rdy...) but what do you think it would take to use ￼￼https://github.com/willemt/uv_multiplex and make a example say test_multicore_tls.c in sample/libuv-tls? 

Thanks again for the project...

**Comment by ljackson** [comment]
it appears I actually got it to work today.. However doesn't perform as well as I expected. What do you think or what have you tested for number of concurrent conns with evt-tls and libuv? As well as how does libuv do connection state/metadata for the app and does evt-tls expose that I can't seem to find it in your apt/structs. Thx

**Comment by ljackson** [comment]
@deleisha you want a pull request or have any thoughts on this ? What I am after is a path to saturating many cores with tls/io ;)

**Comment by deleisha** [comment]
Good to know that you got it working. 

evt-tls will facilitates TLS programming by using, currently only with OpenSSL, as black box. You feed whatever data is received from network(NIO) and read unwrapped data though evt_tls_read.
Implying that network part is handled by libuv and crypto part done by evt-tls and they are independent.

Handling concurrent connection, I do hope, libuv will handle well. 

I did not get exactly your question on state/metadata. Could you please elaborate

**Comment by ljackson** [comment]
re state/metadata: say I want a uuid of the connection so that each time a callback is fired I know which one it is to do some other operation / lookups ? thinking it would have to be somehow added to uv_tls_t in the current codebase but there isn't a void *userdata; field or something like that?

**Comment by deleisha** [comment]
Aah, ok. 
`struct evt_tls_s` has a `void *data`.

`uv_tls_t` is just for demo on how to integrate it with libuv and you can adapt in any way you like. It demonstrate one of the way of integrating but may not be the best way.
May be you can add `void *userdata` as well.

**Comment by deleisha** [comment]
I am closing this out, please feel free to reopen if needed

**Comment by deleisha** [comment]
@ljackson 
A pull request would be great
