### ISSUE TITLE
appears it doesn't (fully) close the connection (fd leak) on sigpipe/epipe?

### ISSUE THREAD

**Issue by ljackson** [deleisha/evt-tls#15]
I added the SIG_IGN in main and i can repro with the tcpkali test of ./evt 

 if you run lsof on the binary you can see the fd(s) are still there and the sockets are in closed but the fd's remain is this normal or a bug? IMO feels like a bug as it would run the system out of fd's real quick...

**Comment by ljackson** [comment]
found the issue I think on evt__tls__op in evt_tls.c on sigpipe...etc and other oddites the close_cb not called:

I changed the condition to:

`    handle_shutdown:
        r = SSL_shutdown(conn->ssl);
        bytes = evt__send_pending(conn);
        if ( (-1 == r || SSL_SENT_SHUTDOWN == r || SSL_ERROR_NONE == r)  && conn->close_cb ) {
            conn->close_cb(conn, r);
        }
        return r;
`

and now all fd's and sockets are closed no matter what.... make sense? The -1 one is odd appears that tcpkali sends a bogus conn first to probe and I get -1 return code on that and ERROR_NONE when sigpipe... SSL_SENT_SHUTDOWN is the value  1 for which you were checking before...etc.

**Comment by deleisha** [comment]
Perhaps we should check `bytes` because in case `ECONNRESET` and other, we know we can right away call close_cb

**Comment by ljackson** [comment]
ok will take your advice here but was my findings based on having a debug printf on op and r value.

**Comment by deleisha** [comment]
`SSL_shutdown` has bitten again. We wanted to be law abiding citizen. We intend to do bidirectional shutdown. 
we don't know if all the peers will send close_notify and wait for close_notify from us or vice versa.

So, Let us take a stand until a better solution come up. Do you have better idea?
1) If we initiate shutdown, we will fire callback when `r == 0;` we will not wait for peer close notify. This will be handled in our code at EVT_TLS_OP_SHUTDOWN case
2) If we receive close_notify from peer, that will be processed by SSL_read returning 0. Now we will processed it by calling `SSL_shutdown` in `handle_shutdown` label.

**Comment by ljackson** [comment]
i don't have a better idea that seem reasonable to me.

**Comment by deleisha** [comment]
Should have fixed with https://github.com/deleisha/evt-tls/commit/d46fd1ac11e9a2b58ad20f8de81cdd9b0e74932c
