### ISSUE TITLE
API Suggestion.

### ISSUE THREAD

**Issue by ToiletCommander** [deleisha/evt-tls#16]
Evt-TLS only supports evt_tls_read()
but libuv has two functions:  
uv_read_start() and uv_read_stop().
1. Is this will automatically stop after you use evt_tls_close? If it is , then it is fine.

**Comment by deleisha** [comment]
Yes, evt_tls_close will close the TLS session. 

A document will come shortly but right now our concentration is on making it production ready and mbedtls support with proper error reporting.
