### ISSUE TITLE
where is uv_read_start?

### ISSUE THREAD

**Issue by hh9527** [deleisha/evt-tls#8]
uv_read_start give a way to alloc buffer by user, but it seemed there is no way to do this with evt_tls.

**Comment by deleisha** [comment]
evt-tls is an abstraction on top of OpenSSL's BIO pair(currently) which can be used with any async library including libuv.
The idea is NIO is handled by library like libuv and fed the received data for processing to evt-tls and which calls us back when processing is done. 
So, It us upto the user to use his nice allocation skills with libuv. evt does not handle that.

We have sample integration with libuv but that does not to be used as it is. It is just for demo.

You can combine it any way you like.

Closing this
